### ISSUE TITLE
Fix workaround for testing

### ISSUE THREAD

**Issue by Markus2101** [Markus2101/StaticCodeMetrics#19]
Think about an idea how to fix the workaround which was introduced in bugfix #18 to provide a quick solution for it.

However, it is not recommended to always copy the changes of the original files into the tests-folder to be tested.

**IDEA:**
Create a script which copies all files in `scm_modules/` into `tests/modules_under_test/` when starting the unit-tests with `run_all_tests.py`. When copying all `import` statements refering to files which start with `scm_modules.` need to be replaced. The replacement might contain, for example, following lines:
```
import sys
sys.path.append('tests/modules_under_test/')
from metrics.instability_metric import InstabilityMetric
```

___________________

**TODO:**

- [x] Copy files from `scm_modules` to `test/testmodules` (PR #23)

- [x] Replace import statements respectively (PR #24)

- [x] Add new script to unit-test call (PR #25)
